apiVersion: v1
kind: Service
metadata:
  name: customer-segmentation-service
spec:
  selector:
    app: customer-segmentation
  ports:
    - protocol: "TCP"
      port: 8501
      targetPort: 8501
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-segmentation
spec:
  selector:
    matchLabels:
      app: customer-segmentation
  replicas: 5
  template:
    metadata:
      labels:
        app: customer-segmentation
    spec:
      containers:
        - name: customer-segmentation
          image: docker.io/rudrakshkarpe/customer-segmentation:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501