apiVersion: v2
kind: Service
metadata:
  name: customer-segmentation
  labels:
    run: customer-segmentation
  namespace: retail  
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
    name: http
  - port: 8080
    protocol: TCP
    name: https
  selector:
    run: customer-segmentation